name: Build PlanetFit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (if available)
        run: |
          if [ -d "tests" ] || [ -f "test_main.py" ]; then
            pip install pytest
            mkdir -p test-results
            pytest --junitxml=test-results/results.xml
          else
            echo "No tests found, skipping pytest."
          fi

      - name: Upload test artifacts (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./test-results/results.xml
